import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { LampContainer } from "@/components/ui/lamp";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Albion ERP System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <LampContainer>
          {children}
        </LampContainer>
      </body>
    </html >
  );
}
